
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle :compinstall filename '/home/dev/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
# End of lines configured by zsh-newuser-install
export XDG_CONFIG_HOME='/home/dev/.config'
eval "$(starship init zsh)"
# Loop through all .zsh files in ~/.zsh directory
for file in $XDG_CONFIG_HOME/zsh/plugins/**/*.zsh; do
  # Check if it's a regular file and not a directory
  if [[ -f "$file" ]]; then
    source "$file"
  fi
done

path+=("/home/dev/.local/bin")
export PATH
